version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: manifest_postgres
    environment:
      POSTGRES_USER: manifest_user
      POSTGRES_PASSWORD: manifest_password
      POSTGRES_DB: manifests_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./manifests:/manifests

volumes:
  postgres_data: 